#!/usr/bin/expect
set timeout -1
set host [lindex $argv 0]
set username [lindex $argv 1]
set password [lindex $argv 2]
set src_dir [lindex $argv 3]
set dest_dir [lindex $argv 4]
set file_name [lindex $argv 5]
spawn scp $src_dir/$file_name $username@$host:$dest_dir/
 expect {
 "(yes/no)?"
  {
  send "yes\n"
  expect "*assword:" { send "$password\n"}
 }
 "*assword:"
{
 send "$password\n"
}
}
expect "100%"
expect eof
